apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
  generation: 1
spec:
  identityProviders:
  - mappingMethod: claim
    name: Cognito
    openID:
      claims:
        email:
        - email
        name:
        - name
        preferredUsername:
        - preferred_username
      clientID: 228b3rdku3661g4085grvbfmle
      clientSecret:
        name: openid-client-secret-4w89h
      extraScopes: []
      issuer: https://sausingers.auth.eu-west-2.amazoncognito.com/oauth2/authorize
    type: OpenID
